# Generated by Django 3.1.13 on 2022-11-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20221027_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='student',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
    ]
