# Generated by Django 4.1.2 on 2023-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_student_address_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
