# Generated by Django 4.1.2 on 2023-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
