# Generated by Django 4.1.2 on 2023-03-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-update', '-created']},
        ),
    ]
