# Generated by Django 3.1.13 on 2022-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20221209_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='notesfile',
        ),
    ]
