# Generated by Django 3.1.13 on 2022-12-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20221209_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notesfile',
            new_name='note_file',
        ),
    ]
