# Generated by Django 3.1.13 on 2022-12-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20221209_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note_file',
            new_name='notefile',
        ),
    ]
