# Generated by Django 3.1.13 on 2022-12-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20221209_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notefile',
            new_name='notesfile',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='sub',
            new_name='subject',
        ),
    ]
