# Generated by Django 4.1.2 on 2023-01-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_notes_options_notes_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-create']},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='created',
            new_name='create',
        ),
    ]
