# Generated by Django 4.1.2 on 2023-01-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_notes_options_notes_created_notes_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='update',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='updated',
        ),
    ]
