# Generated by Django 4.1.2 on 2023-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_notes_options_notes_created_notes_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='update',
        ),
    ]
