# Generated by Django 4.1.2 on 2023-01-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_notes_options_remove_notes_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='update',
            new_name='updated',
        ),
    ]
