# Generated by Django 4.1.2 on 2023-01-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='update',
        ),
    ]
